In [1]:
from dc_utils.dc_sounding import DCSoundingInteract
import numpy as np
import pandas as pd
%matplotlib widget

In [2]:
example_locs = pd.read_csv('data/lab03_positions.csv')
A_x = example_locs['A']
B_x = example_locs['B']
M_x = example_locs['M']
N_x = example_locs['N']

In [3]:
interactor = DCSoundingInteract(A_x, B_x, M_x, N_x)
interactor.display()

In [4]:
# You can drag lines around to update the predicted data
# Try shift clicking on a line segment to insert a new point
# you can pull the arrow downward to extend your working space.

In [7]:
# You can set the current model with
# notice how setting these values changes the interactor above! It is a live object!
rhos = np.array([50 , 100])
thicks = np.array([20])

interactor.set_model(rhos, thicks)

In [9]:
# you can get the current model from the live interactor with
rho, thick = interactor.get_model()
rho, thick

(array([ 50, 100]), array([20]))

In [10]:
# You can retrieve the current forward modeled data with
d_volts = interactor.get_data()
# If you wanted to add noise to this data set you could do:
# d_volts += np.random.randn(*d_volts.shape)* 0.05 * np.abs(d_volts)
# which adds gaussian noise with standard deviation of 5% of the data value
d_volts

array([8.48833725e+00, 2.02118490e+00, 4.99650858e-01, 1.63191400e-01,
       8.56732822e-01, 2.14633660e-01, 6.27736144e-02, 2.45660789e-02,
       1.39176387e-01, 3.77006226e-02, 9.78234348e-03, 3.22914277e-03,
       1.58691211e-03])

In [11]:
# If you have your own data to compare it against, you can load it in as observered voltages, 
# If you have a standard deviation you should also enter that, otherwise it will assume
# a std of 5% of the data values. Note that standard deviation cannot be 0.
interactor2 = DCSoundingInteract(
    A_x, B_x, M_x, N_x, observed_voltage=d_volts, standard_deviation=0.05*d_volts
)
interactor2.display()

In [9]:
# When observed voltages are given, the inversion button is enabled!.
# run it with 1 layer to find the best fitting halfspace
# then add a second layer (shift click on the line segment) and run it with two layers.

In [12]:
interactor2.get_model()

(array([ 50.00003169, 100.00005144]), array([20.00029562]))