In [1]:
from dc_utils.dc_sounding import DCSoundingInteract
import numpy as np
import pandas as pd
%matplotlib widget

In [2]:
example_locs = pd.read_csv('data/lab03_positions.csv')
A_x = example_locs['A']
B_x = example_locs['B']
M_x = example_locs['M']
N_x = example_locs['N']

In [3]:
interactor = DCSoundingInteract(A_x, B_x, M_x, N_x)
interactor.display()

In [4]:
# You can drag lines around to update the predicted data
# Try shift clicking on a line segment to insert a new point
# you can pull the arrow downward to extend your working space.

In [7]:
# You can set the current model with
# notice how setting these values changes the interactor above! It is a live object!
rhos = np.array([50 , 100])
thicks = np.array([10])

interactor.set_model(rhos, thicks)

In [9]:
# you can get the current model from the live interactor with
rho, thick = interactor.get_model()
rho, thick

(array([ 50, 100]), array([10]))

In [10]:
# You can retrieve the current forward modeled data with
d_volts = interactor.get_data()
# If you wanted to add noise to this data set you could do:
d_volts += np.random.randn(*d_volts.shape)* 0.05 * np.abs(d_volts)
# which adds gaussian noise with standard deviation of 5% of the data value
d_volts

array([8.87803130e+00, 2.06545679e+00, 4.90605190e-01, 1.60648963e-01,
       8.35357817e-01, 2.48508406e-01, 7.57826253e-02, 2.97890424e-02,
       1.48856534e-01, 4.25942478e-02, 1.02886832e-02, 3.18984103e-03,
       1.58912125e-03])

In [11]:
# If you have your own data to compare it against, you can load it in as observered voltages, 
# If you have a standard deviation you should also enter that, otherwise it will assume
# a std of 5% of the data values. Note that standard deviation cannot be 0.
interactor2 = DCSoundingInteract(
    A_x, B_x, M_x, N_x, observed_voltage=d_volts, standard_deviation=0.05*d_volts
)
interactor2.display()

In [9]:
# When observed voltages are given, the inversion button is enabled!.
# run it with 1 layer to find the best fitting halfspace
# then add a second layer (shift click on the line segment) and run it with two layers.

In [12]:
interactor2.get_model()

(array([ 50.00003169, 100.00005144]), array([20.00029562]))

In [11]:
lab_7_data_folder = 'data/lab07/'
schlumb_frame = pd.read_csv(lab_7_data_folder + 'lab07_10-8_schlumbergertable-1.csv')
schlumb_frame

AB/2  MN/2  Pa(Ohm-m)  Delta(V/F) (megaOhm)  I (mA)  n  sigma (%)
0    1.0   0.2     17.110              2270.000     200  2        0.0
1    1.4   0.2     17.740              1176.000     200  2        0.0
2    2.0   0.2     17.290               555.900     200  2        0.0
3    3.0   0.2     16.020               227.000     200  2        0.0
4    3.0   0.6     17.040               753.400     200  2        0.0
5    4.0   0.2     13.320               106.300     200  2        0.0
6    4.0   0.6     14.210               347.100     200  2        0.1
7    6.0   0.6      9.881               106.900     100  2        0.6
8    8.0   0.6      7.746                46.990     100  2        1.7
9   10.0   0.6      6.098                23.380     100  2        3.1
10  10.0   2.0      8.000                10.610     100  2        0.2
11  14.0   2.0      7.030                46.620     200  2        0.4
12  14.0   0.6      5.282                10.310     200  2        0.0
13  20.0   2.0      7.469                24.020     200  2        0.0
14  30.0   2.0      7.345                10.440     200  2        0.1
15  40.0   2.0      8.084                 6.449     200  2        0.3

In [12]:
AB_2 = np.asarray(schlumb_frame['AB/2'])
MN_2 = np.asarray(schlumb_frame['MN/2'])
R = np.asarray(schlumb_frame['Delta(V/F) (megaOhm)'])/1000

# this one was written down wrong...
R[10] *= 10

A = AB_2
B = -AB_2
M = MN_2
N = -MN_2

In [13]:
# If you have your own data to compare it against, you can load it in as observered voltages, 
# If you have a standard deviation you should also enter that, otherwise it will assume
# a std of 5% of the data values. Note that standard deviation cannot be 0.
interactor_l7 = DCSoundingInteract(
    A, B, M, N, observed_voltage=R, standard_deviation=0.025*R
)
interactor_l7.display()